# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tcpServer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(789, 495)
        self.open_Button = QtWidgets.QPushButton(Form)
        self.open_Button.setGeometry(QtCore.QRect(110, 420, 75, 23))
        self.open_Button.setObjectName("open_Button")
        self.close_Button = QtWidgets.QPushButton(Form)
        self.close_Button.setGeometry(QtCore.QRect(220, 420, 75, 23))
        self.close_Button.setObjectName("close_Button")
        self.label_ip = QtWidgets.QLabel(Form)
        self.label_ip.setGeometry(QtCore.QRect(110, 300, 47, 12))
        self.label_ip.setObjectName("label_ip")
        self.label_port = QtWidgets.QLabel(Form)
        self.label_port.setGeometry(QtCore.QRect(110, 340, 47, 12))
        self.label_port.setObjectName("label_port")
        self.IP_lineEdit = QtWidgets.QLineEdit(Form)
        self.IP_lineEdit.setGeometry(QtCore.QRect(180, 300, 113, 20))
        self.IP_lineEdit.setObjectName("IP_lineEdit")
        self.port_lineEdit = QtWidgets.QLineEdit(Form)
        self.port_lineEdit.setGeometry(QtCore.QRect(180, 340, 113, 20))
        self.port_lineEdit.setObjectName("port_lineEdit")
        self.receive_textBrowser = QtWidgets.QTextBrowser(Form)
        self.receive_textBrowser.setGeometry(QtCore.QRect(440, 280, 251, 161))
        self.receive_textBrowser.setObjectName("receive_textBrowser")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 461, 41, 31))
        self.label.setObjectName("label")
        self.label_status = QtWidgets.QLabel(Form)
        self.label_status.setGeometry(QtCore.QRect(60, 460, 51, 31))
        self.label_status.setObjectName("label_status")
        self.label_tip = QtWidgets.QLabel(Form)
        self.label_tip.setGeometry(QtCore.QRect(190, 460, 391, 21))
        self.label_tip.setText("")
        self.label_tip.setObjectName("label_tip")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(440, 250, 71, 31))
        self.label_2.setObjectName("label_2")
        self.label_image = QtWidgets.QLabel(Form)
        self.label_image.setGeometry(QtCore.QRect(80, 30, 271, 201))
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(460, 20, 221, 171))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(530, 210, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.open_Button.setText(_translate("Form", "开启服务"))
        self.close_Button.setText(_translate("Form", "关闭服务"))
        self.label_ip.setText(_translate("Form", "IP地址"))
        self.label_port.setText(_translate("Form", "端口号"))
        self.label.setText(_translate("Form", "状态："))
        self.label_status.setText(_translate("Form", "未开启"))
        self.label_2.setText(_translate("Form", "数据接收区"))
        self.pushButton.setText(_translate("Form", "PushButton"))
