# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tcpServer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(789, 495)
        self.open_Button = QtWidgets.QPushButton(Form)
        self.open_Button.setGeometry(QtCore.QRect(30, 420, 75, 23))
        self.open_Button.setObjectName("open_Button")
        self.close_Button = QtWidgets.QPushButton(Form)
        self.close_Button.setGeometry(QtCore.QRect(140, 420, 75, 23))
        self.close_Button.setObjectName("close_Button")
        self.label_ip = QtWidgets.QLabel(Form)
        self.label_ip.setGeometry(QtCore.QRect(30, 300, 47, 12))
        self.label_ip.setObjectName("label_ip")
        self.label_port = QtWidgets.QLabel(Form)
        self.label_port.setGeometry(QtCore.QRect(30, 340, 47, 12))
        self.label_port.setObjectName("label_port")
        self.IP_lineEdit = QtWidgets.QLineEdit(Form)
        self.IP_lineEdit.setGeometry(QtCore.QRect(100, 300, 113, 20))
        self.IP_lineEdit.setObjectName("IP_lineEdit")
        self.port_lineEdit = QtWidgets.QLineEdit(Form)
        self.port_lineEdit.setGeometry(QtCore.QRect(100, 340, 113, 20))
        self.port_lineEdit.setObjectName("port_lineEdit")
        self.receive_textBrowser = QtWidgets.QTextBrowser(Form)
        self.receive_textBrowser.setGeometry(QtCore.QRect(250, 280, 241, 161))
        self.receive_textBrowser.setObjectName("receive_textBrowser")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 461, 41, 31))
        self.label.setObjectName("label")
        self.label_status = QtWidgets.QLabel(Form)
        self.label_status.setGeometry(QtCore.QRect(60, 460, 51, 31))
        self.label_status.setObjectName("label_status")
        self.label_tip = QtWidgets.QLabel(Form)
        self.label_tip.setGeometry(QtCore.QRect(190, 460, 391, 21))
        self.label_tip.setText("")
        self.label_tip.setObjectName("label_tip")
        self.label_receiveRegion = QtWidgets.QLabel(Form)
        self.label_receiveRegion.setGeometry(QtCore.QRect(250, 250, 71, 31))
        self.label_receiveRegion.setObjectName("label_receiveRegion")
        self.label_image = QtWidgets.QLabel(Form)
        self.label_image.setGeometry(QtCore.QRect(70, 50, 271, 201))
        self.label_image.setAutoFillBackground(False)
        self.label_image.setStyleSheet("background-color:rgb(175, 210, 255);")
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.textBrowser_info = QtWidgets.QTextBrowser(Form)
        self.textBrowser_info.setGeometry(QtCore.QRect(460, 20, 221, 91))
        self.textBrowser_info.setObjectName("textBrowser_info")
        self.pushButton_refresh = QtWidgets.QPushButton(Form)
        self.pushButton_refresh.setGeometry(QtCore.QRect(530, 120, 75, 23))
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.label_image_test_tip = QtWidgets.QLabel(Form)
        self.label_image_test_tip.setGeometry(QtCore.QRect(70, 20, 101, 31))
        self.label_image_test_tip.setObjectName("label_image_test_tip")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(530, 160, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_sendRegion = QtWidgets.QLabel(Form)
        self.label_sendRegion.setGeometry(QtCore.QRect(520, 240, 71, 31))
        self.label_sendRegion.setObjectName("label_sendRegion")
        self.send_textEdit = QtWidgets.QTextEdit(Form)
        self.send_textEdit.setGeometry(QtCore.QRect(520, 280, 231, 161))
        self.send_textEdit.setObjectName("send_textEdit")
        self.pushButton_send = QtWidgets.QPushButton(Form)
        self.pushButton_send.setGeometry(QtCore.QRect(680, 450, 75, 23))
        self.pushButton_send.setObjectName("pushButton_send")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.open_Button.setText(_translate("Form", "开启服务"))
        self.close_Button.setText(_translate("Form", "关闭服务"))
        self.label_ip.setText(_translate("Form", "IP地址"))
        self.label_port.setText(_translate("Form", "端口号"))
        self.label.setText(_translate("Form", "状态："))
        self.label_status.setText(_translate("Form", "未开启"))
        self.label_receiveRegion.setText(_translate("Form", "数据接收区"))
        self.pushButton_refresh.setText(_translate("Form", "刷新"))
        self.label_image_test_tip.setText(_translate("Form", "待识别图像："))
        self.pushButton.setText(_translate("Form", "识别"))
        self.label_sendRegion.setText(_translate("Form", "数据发送区"))
        self.pushButton_send.setText(_translate("Form", "发送"))
